databases:
  - name: cms-postgres
    databaseName: strapi
    user: strapi
    plan: free
    region: singapore

services:
  - type: web
    name: cms-strapi
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /_health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: cms-postgres
          property: connectionString
      - key: DATABASE_SSL
        value: "true"
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: STRAPI_TELEMETRY_DISABLED
        value: "true"
      - key: DATABASE_SSL_REJECT_UNAUTHORIZED
        value: "false"
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: cms-redis-key
          property: connectionString
  - type: pserv
    name: cms-loadtest
    runtime: image
    image:
      url: docker.io/grafana/k6:latest
    plan: free
    region: singapore
    envVars:
      - key: K6_PROMETHEUS_RW_SERVER_URL
        value: http://cms-prometheus:9090/api/v1/write
    startCommand: "sleep infinity"
  - type: web
    name: cms-prometheus
    runtime: docker
    dockerfilePath: ./monitoring/prometheus.Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: "9090"
    # disk:
    #   name: prom-data
    #   mountPath: /prometheus
    #   sizeGB: 1
  - type: web
    name: cms-grafana
    runtime: image
    image:
      url: docker.io/grafana/grafana:latest
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: "3000"
      - key: GF_SECURITY_ADMIN_PASSWORD
        generateValue: true
      - key: GF_AUTH_ANONYMOUS_ENABLED
        value: "true"
    # disk:
    #   name: grafana-data
    #   mountPath: /var/lib/grafana
    #   sizeGB: 1
